import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Header from "@/components/common/Header/Header";
import Footer from "@/components/common/Footer/Footer";
import Motion from "@/components/ui/Motion";
import { ToastContainer } from "react-toastify";

const onest = Onest({
  subsets: ["latin"],
  variable: "--font-onest",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${onest.variable} antialiased`}
      >
        <StoreProvider>
          <Header />
          <ToastContainer />
          <Motion>
            {children}
          </Motion>
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
